<a href="https://colab.research.google.com/github/koalanoir/ReseauNeuroneSimple/blob/main/ReseauDeNeuronnesSimple.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np # linear algebra

In [96]:
x=np.array([
    [1,0,0],
     [1,0,1],
      [1,1,0],
       [1,1,1]])
w=np.array([0.3,0.1,-0.2])
yv=np.array([0,0,0,1])

In [97]:
u=0.5

In [53]:
def h(x):
  if x>0:
    return 1
  else:
    return 0


In [21]:
a=np.inner(x,w)
y=h(a)
err=yv-y
print(y)
print(err)

0.15999999999999998
19.84


In [30]:
w=w+u*err*x
print(w)

[11.739992  -9.0519936  3.2319976]


In [67]:
print(x)

[[1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


In [98]:
end=False
iter=len(x)
it=1
while end==False:
  print(it)
  it+=1
  for i in range(iter):
    a=np.inner(x[i],w)
    y=h(a)
    err=yv[i]-y
    e=True
    if err!=0:
      e=False
    w=w+u*err*x[i]
    print("target "+str(i)+" : ")
    print(str(x[i])+" -> "+str(y))
    print("error "+str(i)+" : "+str(e))
    if e==False:
      print(str(x[i])+" -> "+str(yv[i]))
    print(iter)
    if err==0:
      iter-=1
    else:
      iter=len(x)
    if err==0 and iter==0:
      end=True




1
target 0 : 
[1 0 0] -> 1
error 0 : False
[1 0 0] -> 0
4
target 1 : 
[1 0 1] -> 0
error 1 : True
4
target 2 : 
[1 1 0] -> 0
error 2 : True
3
target 3 : 
[1 1 1] -> 0
error 3 : False
[1 1 1] -> 1
2
2
target 0 : 
[1 0 0] -> 1
error 0 : False
[1 0 0] -> 0
4
target 1 : 
[1 0 1] -> 1
error 1 : False
[1 0 1] -> 0
4
target 2 : 
[1 1 0] -> 0
error 2 : True
4
target 3 : 
[1 1 1] -> 0
error 3 : False
[1 1 1] -> 1
3
3
target 0 : 
[1 0 0] -> 0
error 0 : True
4
target 1 : 
[1 0 1] -> 1
error 1 : False
[1 0 1] -> 0
3
target 2 : 
[1 1 0] -> 1
error 2 : False
[1 1 0] -> 0
4
target 3 : 
[1 1 1] -> 0
error 3 : False
[1 1 1] -> 1
4
4
target 0 : 
[1 0 0] -> 0
error 0 : True
4
target 1 : 
[1 0 1] -> 0
error 1 : True
3
target 2 : 
[1 1 0] -> 1
error 2 : False
[1 1 0] -> 0
2
target 3 : 
[1 1 1] -> 0
error 3 : False
[1 1 1] -> 1
4
5
target 0 : 
[1 0 0] -> 0
error 0 : True
4
target 1 : 
[1 0 1] -> 1
error 1 : False
[1 0 1] -> 0
3
target 2 : 
[1 1 0] -> 0
error 2 : True
4
target 3 : 
[1 1 1] -> 1
error 3 : Tru